create table users (
                       id bigint generated by default as identity primary key,
                       email varchar(255) not null unique,
                       password_hash varchar(255) not null,
                       role varchar(255) not null check (role in ('OWNER', 'CASHIER')),
                       created_at timestamp(6) with time zone not null
);