create table products (
                          id             bigint generated by default as identity primary key,
                          name           varchar(255)   not null,
                          sku            varchar(100)   not null unique,
                          description    varchar(1000),
                          price          numeric(12, 2) not null,
                          gst_rate       numeric(5, 2)  not null,
                          hsn_code       varchar(20),
                          stock_quantity integer        not null default 0,
                          created_at     timestamp(6) with time zone not null,
                          updated_at     timestamp(6) with time zone
);