create table invoices (
                           id             bigint generated by default as identity primary key,
                           customer_name  varchar(255),
                           customer_phone varchar(20),
                           subtotal       numeric(12, 2) not null,
                           tax_amount     numeric(12, 2) not null,
                           total_amount   numeric(12, 2) not null,
                           status         varchar(20)    not null default 'COMPLETED'
                               check (status in ('COMPLETED', 'VOID')),
                           created_at     timestamp(6) with time zone not null,
                           voided_at      timestamp(6) with time zone
);

create table invoice_items (
                                id             bigint generated by default as identity primary key,
                                invoice_id     bigint         not null references invoices (id) on delete restrict,
                                product_id     bigint         not null references products (id) on delete restrict,
                                product_name   varchar(255)   not null,
                                sku            varchar(100)   not null,
                                hsn_code       varchar(20),
                                unit_price     numeric(12, 2) not null,
                                gst_rate       numeric(5, 2)  not null,
                                quantity       integer        not null check (quantity > 0),
                                line_subtotal  numeric(12, 2) not null,
                                line_tax       numeric(12, 2) not null,
                                line_total     numeric(12, 2) not null
);

create index idx_invoice_items_invoice_id on invoice_items (invoice_id);
create index idx_invoice_items_product_id on invoice_items (product_id);