create table stores (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null,
    created_at timestamp(6) with time zone not null default now()
);

insert into stores (name, created_at) values ('Default Store', now());

alter table users    add column store_id bigint references stores (id);
alter table products add column store_id bigint references stores (id);
alter table invoices add column store_id bigint references stores (id);

update users    set store_id = (select id from stores where name = 'Default Store');
update products set store_id = (select id from stores where name = 'Default Store');
update invoices set store_id = (select id from stores where name = 'Default Store');

alter table users    alter column store_id set not null;
alter table products alter column store_id set not null;
alter table invoices alter column store_id set not null;

-- SKU uniqueness moves from global to per-store. Look up the auto-generated constraint name
-- dynamically instead of assuming it — this migration only gets one real shot against production.
do $$
declare
    v_constraint_name text;
begin
    select tc.constraint_name into v_constraint_name
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on kcu.constraint_name = tc.constraint_name
     and kcu.constraint_schema = tc.constraint_schema
    where tc.table_schema = current_schema()
      and tc.table_name = 'products'
      and tc.constraint_type = 'UNIQUE'
      and kcu.column_name = 'sku'
    limit 1;

    if v_constraint_name is not null then
        execute format('alter table products drop constraint %I', v_constraint_name);
    else
        raise notice 'No existing unique constraint found on products.sku — check assumptions.';
    end if;
end $$;

alter table products add constraint uq_products_store_sku unique (store_id, sku);

create index idx_users_store_id    on users (store_id);
create index idx_products_store_id on products (store_id);
create index idx_invoices_store_id on invoices (store_id, created_at);