create table invoice_returns (
    id              bigint generated by default as identity primary key,
    store_id        bigint not null references stores (id),
    invoice_id      bigint not null references invoices (id),
    refund_subtotal numeric(12, 2) not null,
    refund_tax      numeric(12, 2) not null,
    refund_total    numeric(12, 2) not null,
    created_at      timestamp(6) with time zone not null default now()
);

create table invoice_return_items (
    id                    bigint generated by default as identity primary key,
    invoice_return_id     bigint         not null references invoice_returns (id),
    invoice_item_id       bigint         not null references invoice_items (id),
    quantity_returned     integer        not null,
    line_subtotal_refund  numeric(12, 2) not null,
    line_tax_refund       numeric(12, 2) not null,
    line_total_refund     numeric(12, 2) not null
);

create index idx_invoice_returns_store_id     on invoice_returns (store_id);
create index idx_invoice_returns_invoice_id   on invoice_returns (invoice_id);
create index idx_invoice_return_items_item_id on invoice_return_items (invoice_item_id);